
services:
#mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
#nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
      - adminer:/var/www/adminer
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb 
      - redis
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always
#redis
  redis:
    build: ./bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
# FTP
  ftp:
    build: ./bonus/ftp
    container_name: ftp
    networks:
      - inception
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress:/var/www/wordpress
# static-site
  static-site:
    build: ./bonus/static-site
    container_name: static-site
    networks:
      - inception
# Adminer 
  adminer:
    build: ./bonus/adminer
    container_name: adminer
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
# Prometheus      
  prometheus:
    build: ./bonus/prometheus
    container_name: prometheus
    networks:
      - inception
#grafana
  grafana:
    build: ./bonus/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - inception
#cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception


# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/$USER/data/wordpress
      o : bind
      type : none
  adminer:
    name: adminer
    driver: local
    driver_opts:
      device: /home/$USER/data/adminer
      o : bind
      type : none
  grafana-data:
    name: grafana
    driver: local
    driver_opts:
      device: /home/$USER/data/grafana
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception